apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syucloud-tls
  namespace: sanhak
spec:
  secretName: syucloud-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  commonName: syucloud.store
  dnsNames:
    - syucloud.store
    - www.syucloud.store